# Generated by Django 2.1.2 on 2018-12-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goeymvcapp', '0002_category_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
