# Generated by Django 2.1.2 on 2018-12-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goeymvcapp', '0005_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='status',
        ),
    ]
